title: Kyle Kirkby
description: > # this means to ignore newlines until "baseurl:"
  I'm a web developer / magician / learner / amateur astronomer
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kylekirkby.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
# Author Settings
author: Kyle Kirkby # add your name
author-img: kyle-kirkby.jpg # add your photo
about-author: I'm a web developer / magician / life learner xD / amateur astronomer # add description
social-twitter: the_actual_kyle # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kylekirkby # add your Github handle
social-linkedin: kylekirkby # add your Linkedin handle
social-email: kylekirkbyy@gmail.com # add your Email address
# Disqus
discus-identifier: https-kylekirkby-github-io # add your discus identifier
# Tracker
analytics: # Google Analytics
# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
paginate: 8
paginate_path: "/page/:num"
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
